export const SCHOOLS = [
  {
    slug: 'harvard',
    name: 'Harvard University',
    newspaper: 'The Harvard Crimson',
    url: 'https://www.thecrimson.com',
    scraperKey: 'crimson',
  },
  {
    slug: 'yale',
    name: 'Yale University',
    newspaper: 'Yale Daily News',
    url: 'https://yaledailynews.com',
    scraperKey: 'ydn',
  },
  {
    slug: 'princeton',
    name: 'Princeton University',
    newspaper: 'The Daily Princetonian',
    url: 'https://www.dailyprincetonian.com',
    scraperKey: 'princetonian',
  },
  {
    slug: 'columbia',
    name: 'Columbia University',
    newspaper: 'Columbia Spectator',
    url: 'https://www.columbiaspectator.com',
    scraperKey: 'spectator',
  },
  {
    slug: 'penn',
    name: 'University of Pennsylvania',
    newspaper: 'The Daily Pennsylvanian',
    url: 'https://www.thedp.com',
    scraperKey: 'dp',
  },
  {
    slug: 'brown',
    name: 'Brown University',
    newspaper: 'The Brown Daily Herald',
    url: 'https://www.browndailyherald.com',
    scraperKey: 'herald',
  },
  {
    slug: 'dartmouth',
    name: 'Dartmouth College',
    newspaper: 'The Dartmouth',
    url: 'https://www.thedartmouth.com',
    scraperKey: 'dartmouth',
  },
  {
    slug: 'cornell',
    name: 'Cornell University',
    newspaper: 'Cornell Daily Sun',
    url: 'https://cornellsun.com',
    scraperKey: 'sun',
  },
  {
    slug: 'stanford',
    name: 'Stanford University',
    newspaper: 'The Stanford Daily',
    url: 'https://stanforddaily.com',
    scraperKey: 'stanforddaily',
  },
  {
    slug: 'mit',
    name: 'MIT',
    newspaper: 'The Tech',
    url: 'https://thetech.org',
    scraperKey: 'thetech',
  },
  {
    slug: 'caltech',
    name: 'Caltech',
    newspaper: 'The California Tech',
    url: 'https://tech.caltech.edu',
    scraperKey: 'caltech',
  },
  {
    slug: 'cmu',
    name: 'Carnegie Mellon University',
    newspaper: 'The Tartan',
    url: 'https://thetartan.org',
    scraperKey: 'tartan',
  },
  {
    slug: 'tufts',
    name: 'Tufts University',
    newspaper: 'Tufts Daily',
    url: 'https://tuftsdaily.com',
    scraperKey: 'tuftsdaily',
  },
  {
    slug: 'gatech',
    name: 'Georgia Tech',
    newspaper: 'The Technique',
    url: 'https://nique.net',
    scraperKey: 'technique',
  },
] as const;

export type SchoolSlug = (typeof SCHOOLS)[number]['slug'];

export const SCHOOL_COLORS: Record<string, string> = {
  harvard: '#A51C30',
  yale: '#00356B',
  princeton: '#E77500',
  columbia: '#003087',
  penn: '#011F5B',
  brown: '#4E3629',
  dartmouth: '#00693E',
  cornell: '#B31B1B',
  stanford: '#8C1515',
  mit: '#A31F34',
  caltech: '#FF6C0C',
  cmu: '#C41230',
  tufts: '#3E8EDE',
  gatech: '#B3A369',
};
